- tap_aggregator/Cargo.toml
- tap_aggregator/README.md
- tap_aggregator/src/api_versioning.rs
- tap_aggregator/src/error_codes.rs
- tap_aggregator/src/jsonrpsee_helpers.rs
- tap_aggregator/src/main.rs
- tap_aggregator/src/server.rs
By API, here we mean specifically the TAP JSON-RPC API version, not the library version.
Maintains a const list of supported API versions, as well as a const list of API versions for which to warn of imminent deprecation. We expect the client to periodically check if its expected API version is deprecated.
For all functions, an expected API version is to be supplied as argument. Each function will have to check if the number is supported, and return an error otherwise.
Rationale:
- The JSON-RPC spec does not allow for deprecation messages. All non-error responses have to be HTTP 204. The design is the result of trying not to break the JSON-RPC spec.
- This is designed for maximum flexibility. The primary goal is to have a reasonable public API. The actual implementation can be improved in …
> feat(aggregator): basic JSON-RPC API version mgmt

- tap_aggregator/README.md
- tap_aggregator/src/error_codes.rs
- tap_aggregator/src/server.rs
- Set errors values as [-32000,-32049]
- Set warning values as [-32050, -32099]
- Removing repeating "Error" and "Warning" postfixes.
fixes #102
> Fix warning code values

- tap_core/Cargo.toml
- tap_core/benches/timeline_aggretion_protocol_benchmark.rs
Updated benchmarks so they compile and run.
closes https://github.com/semiotic-ai/timeline-aggregation-protocol/issues/70
> fix: verification benchmarks

- .github/workflows/release_please.yml
- tap_aggregator/Cargo.toml
- tap_core/Cargo.toml
- tap_integration_tests/Cargo.toml
- A few fixes / adjustments to `cargo.toml`s make publishing possible.
- Using a Github App token for `release-please`, so that its PRs can run CI. [More info here](https://github.com/peter-evans/create-pull-request/blob/5f8399b325911a0981ba132a51cceecce543d255/docs/concepts-guidelines.md#authenticating-with-github-app-generated-tokens)
- Adding a `cargo workspaces publish` step after `release-please`. Runs only if a new release is created.
> Cargo publish

- tap_aggregator/Cargo.toml
- tap_integration_tests/Cargo.toml
The lack of a version upsets `cargo publish`.
`release-please` will update the version of local `path` dependencies automatically.
> build: fix local deps versions.

- tap_core/src/adapters/rav_storage_adapter.rs
- tap_core/src/adapters/test/rav_storage_adapter_mock.rs
- tap_core/src/adapters/test/rav_storage_adapter_test.rs
- tap_core/src/eip_712_signed_message.rs
- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_integration_tests/tests/showcase.rs
Simplifying the trait to the minimum that is needed for the TAP manager to function: only needs to store and retrieve the last RAV for each allocation. The user is free to add more functionality if needed.
BREAKING CHANGE: the RavStorageAdapter public trait has changed
> refactor(rav_storage_adapter)!: simplify trait

- tap_core/src/adapters/receipt_storage_adapter.rs
- tap_core/src/adapters/test/receipt_storage_adapter_mock.rs
Makes functions that take ranges generic over the type of range (inclusive, exclusive, UpTo, etc).
I need this to concisely implement a solution for #108 , and perhaps later also prune the trait further.
> feat(receipt_storage_adapter): Use RangeBounds

- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_core/src/tap_receipt/receipt_auditor.rs
Added a test (that initially failed):
- Create 20 receipts with consecutive timestamps (eg. 1, 2, 3...)
- Receive the first 10
- Create RAV
- Receive remaining 10
- Create RAV (w/ previous RAV)
- Check failed receipts and total expected amount
The fix is self-explanatory.
> Fix: Receipts w/ consecutive timestamps failed

- tap_core/src/adapters/receipt_storage_adapter.rs
- tap_core/src/adapters/test/receipt_storage_adapter_mock.rs
BREAKING CHANGE: all functions unnecessary to the TAP manager have been removed from the `ReceiptStorageAdapter` trait.
Note: `remove_receipts_in_timestamp_range` will be made necessary by #130
> refactor(receipt_storage_adapter)!: prune trait

- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
`receipts_auto_delete` is a function that deletes receipts that are older than the last RAV.
Had to hack a bit with the tests to reduce code duplication:
- Using a test matrix instead of cases in `manager_create_multiple_rav_requests_all_valid_receipts_consecutive_timestamps`. The tests will run with and without the "receipts auto delete" right before the 1st and 2nd RAV.
- To make sure that the right number of receipts gets deleted, I needed to access the private `receipt_storage_adapter` attribute of `Manager`. Since the tests were originally outside the `Manager` source file (integration tests), I created a test helper function in the `Manager` source file that exposes the private `receipt_storage_adapter` attribute.
Fixes #108
> feat(manager): add receipts_auto_delete

- .github/workflows/tests.yml
We can't rely on `cargo llvm-cov test`, which doesn't by default because of https://github.com/taiki-e/cargo-llvm-cov/issues/2
> ci: test doc's code snippets

- tap_aggregator/src/main.rs
Error was:
```
thread 'main' panicked at 'Command tap_aggregator: Short option names must be unique for each argument, but '-m' is in use by both 'mnemonic' and 'max_request_body_size''
```
Short arguments had to be removed as they clashed (`-m`). Short arguments are not required, so removal is the easy fix.
> fix(aggregator): short args removed

- tap_core/Cargo.toml
This removes some unused dependencies from tap_core.
```bash
$ (cd tap_core && cargo tree | wc -l) # before
842
$ (cd tap_core && cargo tree | wc -l) # after
783
```
> chore: cleanup tap_core deps

- .github/workflows/tests.yml
- tap_aggregator/src/aggregator.rs
- tap_aggregator/src/main.rs
- tap_core/src/adapters/test/receipt_checks_adapter_test.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_integration_tests/clippy.toml
- tap_integration_tests/tests/indexer_mock/mod.rs
- tap_integration_tests/tests/showcase.rs
2 fixes for the clippy checks:
- Fail on warnings
- `--all-targets`, which somehow unearthed a lot of warnings
Then I fixed all the warnings in several passes.
> ci: fix clippy

- tap_core/src/tap_receipt/mod.rs
- tap_core/src/tap_receipt/received_receipt.rs
So that `ReceivedReceipt` instances can be easily stored in external storage.
Need this for the WIP integration into indexer-service-rs.
> feat: serde for ReceivedReceipt

- tap_core/src/adapters/receipt_checks_adapter.rs
- tap_core/src/adapters/test/receipt_checks_adapter_mock.rs
- tap_core/src/adapters/test/receipt_checks_adapter_test.rs
- tap_core/src/tap_receipt/receipt_auditor.rs
BREAKING CHANGE: All ReceiptChecksAdapter trait method now return Result. Makes it possible to return Adapter errors besides just check failures.
> refactor(core)!: make ChecksAdapter return Result

- tap_core/Cargo.toml
- tap_integration_tests/Cargo.toml
Fixes a build issue with v0.3.1 and the rest of our dependencies. The previous PR didn't update in all the Cargo.toml files, and in particular not in core.
> fix: Update alloy to v0.3.2

- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_integration_tests/tests/indexer_mock/mod.rs
BREAKING CHANGE:
`tap_core::tap_manager::manager::Manager::verify_and_store_receipt` now takes a slice of initial_checks instead of a Vec.
> refactor(core): manager arg slice instead of vec

- tap_aggregator/Cargo.toml
- tap_core/Cargo.toml
- tap_integration_tests/Cargo.toml
Among other things, this is to make `tap_core` play nice with other dependencies used in `indexer-service-rs`.
> chore: update alloy-primitives and alloy-sol-types

- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_core/src/tap_receipt/receipt_auditor.rs
- tap_core/src/tap_receipt/received_receipt.rs
The checks are specifically made to check the receipts that are to be aggregated only in their own context. Helps for uniqueness checks for example, where we avoid calling the storage backend and only check that the collected receipts are unique.
In terms of the public API, this should be a cleaner solution than #179 . The implementation itself is not super clean though. A deeper refactor of tap_core may help make this a bit less hacky.
> refactor(core): collect runs batched checks

- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
Remove unnecessary mutability that makes usage a little bit harder.
> fix: mutable manager.remove_obsolete_receipts

- tap_aggregator/README.md
- tap_aggregator/src/main.rs
- tap_core/src/adapters/escrow_adapter.rs
- tap_core/src/adapters/receipt_checks_adapter.rs
- tap_core/src/adapters/test/escrow_adapter_mock.rs
- tap_core/src/adapters/test/escrow_adapter_test.rs
- tap_core/src/adapters/test/receipt_checks_adapter_mock.rs
- tap_core/src/adapters/test/receipt_checks_adapter_test.rs
- tap_core/src/error.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_core/src/tap_receipt/receipt_auditor.rs
- tap_core/src/tap_receipt/tests/received_receipt_tests.rs
- tap_integration_tests/tests/showcase.rs
> refactor!: rename "gateway" to "sender" everywhere

- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/rav_request.rs
Helps the user determine why the receipts failed, because ReceivedReceipt contains the status of checks.
> feat!: create_rav_request() returns invalid ReceivedReceipt

- tap_core/Cargo.toml
- tap_core/src/adapters/receipt_storage_adapter.rs
- tap_core/src/adapters/test/receipt_storage_adapter_mock.rs
- tap_core/src/adapters/test/receipt_storage_adapter_test.rs
- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_integration_tests/tests/indexer_mock/mod.rs
Helps with keeping the rule of 15,000 max receipts per aggregation request.
Also adds a helper function to implement the limit safely.
I started getting
```
error[E0599]: no function or associated item named `new` found for struct `tokio::runtime::Runtime` in the current scope
--> tap_core/benches/timeline_aggretion_protocol_benchmark.rs:49:34
|
49 |     let async_runtime = Runtime::new().unwrap();
|                                  ^^^ function or associated item not found in `Runtime`
```
Not sure why it even started happening, but the fix was to add the `rt-multi-thread` feature to `tokio` :shrug:
> feat!: add limit to receipts retrieve

- tap_core/src/adapters/mock/receipt_checks_adapter_mock.rs
- tap_core/src/adapters/mock/receipt_storage_adapter_mock.rs
- tap_core/src/adapters/receipt_storage_adapter.rs
- tap_core/src/adapters/test/receipt_checks_adapter_test.rs
- tap_core/src/adapters/test/receipt_storage_adapter_test.rs
- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/rav_request.rs
- tap_core/src/tap_receipt/mod.rs
- tap_core/src/tap_receipt/receipt_auditor.rs
- tap_core/src/tap_receipt/received_receipt.rs
- tap_core/src/tap_receipt/tests/received_receipt_tests.rs
- tap_integration_tests/tests/showcase.rs
- Using typestate pattern for `ReceivedReceipt` state machine
- States are now enforced by compile time and don't need to be checked by tests
- Transitions consume the old value creating a new state
```mermaid
graph TD;
Checking-->AwaitingReserve;
AwaitingReserve-->Reserved;
Checking-->Failed;
AwaitingReserve-->Failed;
```
- The manager was not using rav statuses
- Implementation in tap-agent was not using it
- Removed from tests
- Escrow check was a special optional check (a ReceivedReceipt may or may not have the required check)
- Escrow reserve is now a mandatory state
- Must be executed after all checks have passed
> refactor!: use typestate for receivedreceipt

- tap_aggregator/Cargo.toml
- tap_core/Cargo.toml
- tap_integration_tests/Cargo.toml
Recently, a new major version of the alloy-rs crates has been released. 
As this version is incompatible with the previous one in "semver terms", this PR updates the version to the latest one.
> chore(deps): update alloy-rs core types monorepo to 0.6.0

- tap_aggregator/Cargo.toml
- tap_aggregator/src/aggregator.rs
- tap_aggregator/src/main.rs
- tap_aggregator/src/server.rs
- tap_core/src/error.rs
- tap_integration_tests/tests/showcase.rs
Lets the aggregator accept receipts or input RAVs that are signed with other keys.
Helpful with dealing with the transition when rotating keys, or making sure that we can accept receipts signed by other signing keys belonging to the same Sender (multiple locations with different keys for example).
Fixes #205
> feat(aggregator): Add support for multiple signers in input

- tap_aggregator/src/aggregator.rs
- tap_aggregator/src/server.rs
- tap_core/src/receipt_aggregate_voucher.rs
- tap_core/src/tap_manager/manager.rs
- tap_core/src/tap_manager/test/manager_test.rs
- tap_integration_tests/tests/showcase.rs
Signed-off-by: Gustavo Inacio <gustavo@semiotic.ai>
> fix!: update rav attributes to camel case

- tap_aggregator/Cargo.toml
- tap_core/Cargo.toml
- tap_integration_tests/Cargo.toml
Recently, a new "major" version of the alloy-rs crates has been released. 
As this version is incompatible with the previous one in "semver terms", this PR updates the version to the latest one.
> chore(deps): update alloy-rs core types monorepo to 0.7.0

- tap_core/src/receipt/checks.rs
- tap_core/tests/manager_test.rs
Added extra unit tests for:
- batch timestamp check for receipts
- batch uniqueness check for receipts
- ignore invalid receipts for rav creation
- deny rav due to wrong value
> Cover more unit tests on rav/receipts

- .github/workflows/tests.yml
- Dockerfile.tap_aggregator
- tap_aggregator/Cargo.toml
- tap_aggregator/src/aggregator.rs
- tap_aggregator/src/main.rs
- tap_aggregator/src/server.rs
- tap_core/Cargo.toml
- tap_core/benches/timeline_aggretion_protocol_benchmark.rs
- tap_core/src/error.rs
- tap_core/src/lib.rs
- tap_core/src/manager/adapters/escrow.rs
- tap_core/src/manager/context/memory.rs
- tap_core/src/manager/mod.rs
- tap_core/src/manager/tap_manager.rs
- tap_core/src/rav.rs
- tap_core/src/receipt/checks.rs
- tap_core/src/receipt/error.rs
- tap_core/src/receipt/receipt_sol.rs
- tap_core/src/receipt/received_receipt.rs
- tap_core/src/signed_message.rs
- tap_core/tests/escrow_test.rs
- tap_core/tests/manager_test.rs
- tap_core/tests/rav_test.rs
- tap_core/tests/receipt_test.rs
- tap_core/tests/received_receipt_test.rs
- tap_integration_tests/Cargo.toml
- tap_integration_tests/tests/indexer_mock.rs
- tap_integration_tests/tests/showcase.rs
> refactor!(all): remove ethers and use alloy

- tap_core/src/manager/tap_manager.rs
- tap_core/src/rav/request.rs
- tap_core/tests/manager_test.rs
- tap_integration_tests/tests/indexer_mock.rs
This goes in hand with [#214](https://github.com/graphprotocol/indexer-rs/issues/214) in indexer-rs
Currently we have an issue were if all receipts are invalid when calling [create_rav_request](https://github.com/semiotic-ai/timeline-aggregation-protocol/blob/main/tap_core/src/manager/tap_manager.rs#L182) > [generate_expect_rav](https://github.com/semiotic-ai/timeline-aggregation-protocol/blob/main/tap_core/src/manager/tap_manager.rs#L207) it turns back an **[error](https://github.com/semiotic-ai/timeline-aggregation-protocol/blob/main/tap_core/src/manager/tap_manager.rs#L212)** and cant go on with moving the **invalid** receipts to the `failed_receipts` table
~Considered modifying that function but its good to have that error to understand what is going on. So im adding another function …
> obtain invalid receipts

- tap_core/src/manager/context/memory.rs
- tap_core/src/manager/tap_manager.rs
- tap_core/src/receipt/checks.rs
- tap_core/src/receipt/error.rs
- tap_core/src/receipt/received_receipt.rs
- tap_core/tests/manager_test.rs
- tap_core/tests/received_receipt_test.rs
> feat!: add retryable errors to checks

- tap_core/Cargo.toml
- tap_core/src/manager/context/memory.rs
- tap_core/src/manager/mod.rs
- tap_core/src/manager/tap_manager.rs
- tap_core/src/rav.rs
- tap_core/src/receipt/checks.rs
- tap_core/src/receipt/mod.rs
- tap_core/src/receipt/received_receipt.rs
- tap_core/tests/manager_test.rs
- tap_core/tests/received_receipt_test.rs
- tap_integration_tests/tests/indexer_mock.rs
> feat!: add context to checks

- Cargo.toml
- tap_core/src/signed_message.rs
This pull request includes updates to dependencies and some code restructuring to improve compatibility and maintainability. The most important changes include upgrading the `alloy` dependency and restructuring imports in the `tap_core/src/signed_message.rs` file.
Dependency updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L12-R12): Upgraded `alloy` dependency from version `0.5.4` to `0.6`.
New version compatibility changes:
* [`tap_core/src/signed_message.rs`](diffhunk://#diff-703ea6a00960e5a0ceac7afceb445cd614bdc6e7788a615aadf0d56ac2b61607L30-R31): Restructured imports to use `PrimitiveSignature` from `alloy::primitives` and adjusted other related imports.
> chore(deps): update rust crate alloy to v0.6

- .github/workflows/tests.yml
- Cargo.toml
- Dockerfile.tap_aggregator
- tap_core/benches/timeline_aggretion_protocol_benchmark.rs
This pull request includes a version update to the `alloy` dependency in the `Cargo.toml` file. The version has been incremented from `0.6` to `0.7`.
Dependency update:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L12-R12): Updated `alloy` dependency from version `0.6` to `0.7`.
> chore(deps): update rust crate alloy to v0.7

- Cargo.toml
This pull request includes an update to the `Cargo.toml` file to upgrade the version of the `alloy` dependency.
Dependency version update:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L12-R12): Updated the `alloy` dependency from version `0.7` to `0.8`.
> chore(deps): update rust crate alloy to v0.8

- .github/workflows/tests.yml
- Dockerfile.tap_aggregator
- tap_aggregator/Cargo.toml
- tap_aggregator/build.rs
- tap_aggregator/proto/tap_aggregator.proto
- tap_aggregator/src/grpc.rs
- tap_aggregator/src/lib.rs
- tap_aggregator/src/main.rs
- tap_aggregator/src/server.rs
- tap_aggregator/src/tap_aggregator.rs
- tap_aggregator/tests/aggregate_test.rs
- tap_integration_tests/tests/showcase.rs
Signed-off-by: Gustavo Inacio <gustavo@semiotic.ai>
> feat: accept grpc requests in tap-aggregator

- tap_aggregator/Cargo.toml
- tap_aggregator/src/aggregator.rs
Adding rayon to signatures makes it ~4,5x faster
Without Rayon:
1k receipts: 2.4832964
10k receipts: 24.968279
With Rayon:
1k receipts: 0.541488
10k receipts: 5.4854965
> perf: add rayon to verify signatures process

- .github/workflows/tests.yml
- rustfmt.toml
- tap_aggregator/src/aggregator.rs
- tap_aggregator/src/main.rs
- tap_aggregator/src/server.rs
- tap_aggregator/tests/aggregate_test.rs
- tap_core/benches/timeline_aggretion_protocol_benchmark.rs
- tap_core/src/error.rs
- tap_core/src/manager/context/memory.rs
- tap_core/src/rav.rs
- tap_core/src/rav/request.rs
- tap_core/src/receipt/checks.rs
- tap_core/src/receipt/receipt_sol.rs
- tap_core/src/receipt/received_receipt.rs
- tap_core/tests/escrow_test.rs
- tap_core/tests/rav_test.rs
- tap_core/tests/receipt_test.rs
- tap_integration_tests/tests/indexer_mock.rs
- tap_integration_tests/tests/showcase.rs
This pull request includes several changes aimed at improving code organization and formatting across multiple files, as well as updates to the GitHub Actions workflow. The most important changes include the reorganization of imports, enabling nightly features for Rust formatting, and updating the GitHub Actions workflow for formatting checks.
* Reorganized imports to group them more logically and improve readability across multiple files (`tap_aggregator/src/aggregator.rs`, `tap_aggregator/src/main.rs`, `tap_aggregator/src/server.rs`, `tap_aggregator/tests/aggregate_test.rs`, `tap_core/benches/timeline_aggretion_protocol_benchmark.rs`, `tap_core/src/error.rs`, `tap_core/src/manager/context/memory.rs`, `tap_core/src/rav.rs`, `tap_core/src/rav/request.rs`, `tap_core/src/receipt/checks.rs`, …
> refactor: format imports using cargo fmt

- README.md
- tap_aggregator/README.md
Adding reference to the useful [gateway docs on TAP](https://github.com/edgeandnode/gateway/blob/main/README.md#tap)!
> docs(README): link to crate-level docs and say what aggregator is

- Cargo.toml
- tap_aggregator/Cargo.toml
- tap_core/Cargo.toml
- tap_integration_tests/Cargo.toml
- tap_integration_tests/tests/indexer_mock.rs
Tidying up for easier readability and updating dependency versions where easy to do.
> Update and organize dependencies

- tap_aggregator/src/aggregator.rs
- tap_core/src/error.rs
- tap_core/src/manager/adapters/receipt.rs
- tap_core/src/manager/context/memory.rs
- tap_core/src/manager/mod.rs
- tap_core/src/manager/tap_manager.rs
- tap_core/src/rav.rs
- tap_core/src/rav/request.rs
- tap_core/src/receipt/checks.rs
- tap_core/src/receipt/mod.rs
- tap_core/src/receipt/receipt_sol.rs
- tap_core/src/receipt/received_receipt.rs
- tap_core/src/signed_message.rs
- tap_core/tests/manager_test.rs
- tap_core/tests/receipt_test.rs
- tap_core/tests/received_receipt_test.rs
- tap_integration_tests/tests/indexer_mock.rs
- tap_integration_tests/tests/showcase.rs
- Add new Traits WithUniqueId and WithValueAndTimestamp
- implement WithUniqueId and WithValueAndTimestamp for SignedReceipt
- ReceiptWithState generic over the receipt
- RAVRequest generic over receipt
- Manager generic over receipt (can only collect receipts for SignedReceipt for now)
- Checklist generic over receipt
- Functions that previously needed timestamp_ns and value from receipt now uses generic with WithValueAndTimestamp bounds
> refactor!: manager generic over receipt

- tap_aggregator/src/grpc.rs
- tap_aggregator/tests/aggregate_test.rs
- tap_core/src/error.rs
- tap_core/src/manager/adapters/rav.rs
- tap_core/src/manager/context/memory.rs
- tap_core/src/manager/mod.rs
- tap_core/src/manager/tap_manager.rs
- tap_core/src/rav.rs
- tap_core/src/rav/request.rs
- tap_core/tests/manager_test.rs
- tap_core/tests/rav_test.rs
- tap_integration_tests/tests/indexer_mock.rs
- tap_integration_tests/tests/showcase.rs
- Rename InvalidReceivedRAV to InvalidReceivedRav and change it to String
- Update RAVStore and RAVRead to be generic over RAV
- Manager Generic over Rav
- Implement WithValueAndTimestamp for ReceiptAggregateVoucher
- New `Aggregate` trait to be implemented in Ravs
- implement Aggregate for ReceiptAggregateVoucher (using Manager::generate_expected_rav)
- Update RavRequest to be generic over Rav
- Rename RAVRead and RAVStore to RavRead and RavStore
- Rename SignedRAV to SignedRav
> refactor!: make manager generic over rav

- .github/workflows/release_please.yml
By changing to Rust image, sudo is not available (possibly because it has root permission)
https://github.com/semiotic-ai/timeline-aggregation-protocol/actions/runs/13036335498/job/36367623892
> ci: remove sudo from protobuf install

- tap_aggregator/Cargo.toml
- tap_aggregator/src/server.rs
- Endpoint used for sanity / verify purposes.
```json
{
"jsonrpc": "2.0",
"id": 0,
"result": {
"data": {
"name": "TAP",
"version": "1",
"chainId": "0x1",
"verifyingContract": "0x0000000000000000000000000000000000000000"
}
}
}
```
> feat: add eip712domain_info API Endpoint

- .github/workflows/release_please.yml
My intention is that this fixes our [release issue in CI](https://github.com/semiotic-ai/timeline-aggregation-protocol/actions/runs/14046408837/job/39328084893) so that we can release a crate using `thegraph-core` alloy dependencies. This in turn will allow us to tidy up in that area on indexer-rs.
> ci: add libsasl2-dev dependency to CI workflow

- Cargo.toml
- tap_aggregator/Cargo.toml
- tap_aggregator/src/server.rs
- tap_core/Cargo.toml
- tap_core/tests/receipt_test.rs
- tap_graph/src/v1/receipt.rs
- tap_graph/src/v2/receipt.rs
- tap_integration_tests/Cargo.toml
- tap_integration_tests/tests/showcase.rs
- tap_receipt/Cargo.toml
Using the workspace manifest where plausible, updating to latest where it's simple.
> build: centralize dependency imports in workspace manifest

- Cargo.toml
- tap_aggregator/Cargo.toml
This will allow us to update axum where tap aggregator is used, such as indexer-rs. See, for example [https://github.com/graphprotocol/indexer-rs/pull/699](https://github.com/graphprotocol/indexer-rs/pull/699).
> build: update axum to latest along with tonic

- Cargo.toml
- tap_core/tests/rav_test.rs
- tap_core/tests/receipt_test.rs
- tap_eip712_message/src/lib.rs
We need to update our alloy dependencies here in order to update them when we upgrade TAP as a dependency of indexer-rs.
> build: update thegraph-core (alloy) to 0.14.0

- Cargo.toml
Forgot we need to squash to trigger a release ... I want to publish the crate so we can use it in indexer-rs
> build: update clap version to latest (to trigger release)

- tap_aggregator/src/aggregator/v1.rs
- tap_aggregator/src/aggregator/v2.rs
- tap_core/src/manager/tap_manager.rs
- tap_core/tests/manager_test.rs
- tap_core/tests/received_receipt_test.rs
- tap_eip712_message/src/lib.rs
- tap_receipt/src/checks.rs
- tap_receipt/src/lib.rs
This PR improves the security of receipt deduplication by making it resistant to signature malleability attacks. The implementation now identifies receipts based on their message content and recovered signer, rather than just raw signature bytes.
- Replaced `unique_hash` method to `Eip712SignedMessage` that combines message content and signer address
- Updated `check_signatures_unique` to use this malleation-resistant approach
- Added test case demonstrating the signature malleability issue and verifying the fix
> fix: improve receipt deduplication with signature normalization

- tap_aggregator/src/aggregator/v1.rs
- tap_aggregator/src/aggregator/v2.rs
- tap_core/src/manager/tap_manager.rs
- tap_core/tests/manager_test.rs
- tap_core/tests/received_receipt_test.rs
- tap_eip712_message/src/lib.rs
- tap_receipt/src/checks.rs
- tap_receipt/src/lib.rs
I was just reading the report and @severiano-sisneros 's notes more carefully and this seems like a more elegant solution to #291, without pulling in what was essentially a bit of test infra into the broader system. So this PR reverts much of that one. Note the test from #291 is still passing though!
> refactor(eip712): simplify message unique id

- Cargo.toml
- tap_aggregator/Cargo.toml
- tap_core/Cargo.toml
- tap_graph/Cargo.toml
- tap_integration_tests/Cargo.toml
- tap_receipt/Cargo.toml
Some overdue tidying that will hopefully also trigger a release so we can update our alloy dependencies in our published crates!
> fix: better organize dependencies

- Cargo.toml
This just keeps the crate versions for crates from this workspace that we're importing at the latest versions.
> fix(Cargo.toml): bump workspace crate versions

- Cargo.toml
- tap_aggregator/src/server.rs
- tap_core/Cargo.toml
- tap_integration_tests/tests/indexer_mock.rs
Just a dependency with a breaking change.
> build: update jsonrpsee crates

- tap_aggregator/Cargo.toml
- tap_aggregator/src/server.rs
This:
- add a layer to limit number concurrent request
> fix: add layer to set concurrent limits for gRPC

- .github/workflows/release_please.yml
Still out on a limb seeing if the issue [here](https://github.com/semiotic-ai/timeline-aggregation-protocol/actions/runs/15174930398/job/42673246346) is something we can fix without assuming it's a cargo workspace issue.
> fix: clean target directory in ci release workflow

- .github/workflows/release_please.yml
- Cargo.toml
We were not using the most recent `tap_aggregator` crate version in our workspace manifest and this would make sense as a reason for our [release-please CI pipeline failures](https://github.com/semiotic-ai/timeline-aggregation-protocol/actions/runs/15174930398/job/42673246346).
Since a previously attempted fix did not help this PR also reverts [that change](https://github.com/semiotic-ai/timeline-aggregation-protocol/pull/304/commits/8e39ceb4cfa66c179d7410ff7e1008211bef7cfc).
> fix: update tap aggregator version

- Cargo.toml
- tap_aggregator/Cargo.toml
- tap_aggregator/README.md
- tap_aggregator/src/lib.rs
- tap_aggregator/src/protocol_mode.rs
- tap_aggregator/src/receipt_classifier.rs
- tap_aggregator/src/server.rs
This PR introduces the `aggregate_receipts_v2` JSON-RPC endpoint, enabling collection-based receipt aggregation for the Horizon protocol. It maintains full backward compatibility with existing V1 endpoints while supporting a new V2 receipt structure.
---
- **New JSON-RPC Method**: `aggregate_receipts_v2`
- **Updated Receipt Format**:
- `collection_id` (replaces `allocation_id`)
- `payer`, `data_service`, `service_provider` (new fields)
- **Feature-Flagged**: Controlled by the `v2` feature flag (enabled by default)
---
- **Protocol Mode**: Introduces `ProtocolMode` enum (`Legacy` vs `Horizon`)
- **Receipt Classification**: Centralized validation and protocol detection logic in `receipt_classifier.rs`
- **Structured Validation**:
- Validates `collection_id`, `payer`, `data_service`, …
> feat(tap-aggregator): add v2 endpoint
